### PR TITLE
fix path in readme

### PR DESCRIPTION
**Pull request by butonic**
leftover I guess

### CODE REVIEW

**Comment by Instagit** [comment]
Yes, that's from the old video player app. Thanks!

**Comment by jancborchardt** [comment]
@instagit always delete branches after merge :) nust press the "Delete branch" button here.

**Comment by jancborchardt** [comment]
Also, since this app is shipped with ownCloud, we should mention that in the readme?

**Comment by Instagit** [comment]
Now that the repo is under the owncloud namespace, I guess one can assume that it's also shipped with ownCloud, but I guess we could mention it.

That reminds me that I should delete the app from apps.owncloud.com.

**Comment by jancborchardt** [comment]
Yup, cool stuff! :) Again, good to have you on board @Instagit! It’s a really slick video player

**Pull request merged**
