### PR TITLE
Show current/total time

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/files_videoplayer/issues/59 https://github.com/owncloud/files_videoplayer/issues/78 

Screenshot 
screenshot_20190114_211632

### CODE REVIEW

**Comment by voroyam** [comment]
@VicDeo is there an ETA for the new Release?

**Comment by PVince81** [comment]
The video player is bundled and has no marketplace entry, so the fix will be in the upcoming 10.1.0.

I'm not sure if we want to release the video player to marketplace as we have a new player (https://github.com/owncloud/files_mediaviewer) in the works. cc @pmaier1

**Comment by voroyam** [comment]
Not sure what to tell the customer. 
On the one hand - Great news we have fixed it. 
On the other hand - it may not get released.
No critique here, just thinking out loud.

**Comment by PVince81** [comment]
> it may not get released

it will definitely be released with ownCloud Server 10.1.0.
tell them to wait for that version then upgrade

alternatively you can have them apply the patch, which is likely to work on the 10.0.10 version of files_videoplayer

**Comment by voroyam** [comment]
Okay, thanks @PVince81

**Comment by PVince81** [comment]
stable10: ab2c70d5ec9fcb5bfa4b14b354d9bc6ba6336707

seems we missed releasing this with 10.1 due to missing backport. will be in 10.2

**Pull request merged**
