### PR TITLE
Get rid of Flash fallback

### PR DESCRIPTION
**Pull request by LukasReschke**
No way we're getting this into the release ;)

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975 @jancborchardt THX

**Comment by jancborchardt** [comment]
Always also cc @Instagit please for review.

**Comment by DeepDiver1975** [comment]
rebase please

**Comment by LukasReschke** [comment]
Rebased.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
The flash fallback was only for some versions of IE anyway, right? cc @Instagit?

**Comment by Instagit** [comment]
Only IE8, which no longer needs to be supported.

**Comment by jancborchardt** [comment]
Cool cool!

**Pull request merged**
